// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqr_Zg0pQIrVHpKcfoMZlhKcWIE8zP-1Y',
    appId: '1:579668766530:web:ca5978f7faec9cef1c22db',
    messagingSenderId: '579668766530',
    projectId: 'shifty99',
    authDomain: 'shifty99.firebaseapp.com',
    storageBucket: 'shifty99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY37oh9O2Ib8QUM32Bx3K_nPcm2kaWjD4',
    appId: '1:579668766530:android:1fe907aad2e699511c22db',
    messagingSenderId: '579668766530',
    projectId: 'shifty99',
    storageBucket: 'shifty99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3UramoW-4Snt-U2YmF19VbMX3E1tBuA',
    appId: '1:579668766530:ios:791c876bee0a70921c22db',
    messagingSenderId: '579668766530',
    projectId: 'shifty99',
    storageBucket: 'shifty99.appspot.com',
    iosClientId: '579668766530-eesmonsa766ki1umimqbc9nvkumlp6eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationNote',
  );
}
