// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtS_0qKXhoUhBYcs8kzFb2h1L8A-NOW9k',
    appId: '1:111550009835:web:421b6520249edcbf8b89ae',
    messagingSenderId: '111550009835',
    projectId: 'notes-67778',
    authDomain: 'notes-67778.firebaseapp.com',
    storageBucket: 'notes-67778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEL_VRdgUhMzNuBJniRr96KRjRFcRs8wc',
    appId: '1:111550009835:android:065d8bcd07ef04118b89ae',
    messagingSenderId: '111550009835',
    projectId: 'notes-67778',
    storageBucket: 'notes-67778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB869HPn6Z1ErHlI-2SV3M-fm83lhZfP2o',
    appId: '1:111550009835:ios:b469f1e47adf7e238b89ae',
    messagingSenderId: '111550009835',
    projectId: 'notes-67778',
    storageBucket: 'notes-67778.appspot.com',
    iosClientId: '111550009835-bt0dablgpinq57rrub06239oivkcohpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationNote',
  );
}
